### ISSUE TITLE
How can I calculate the sub score?

### ISSUE THREAD

**Issue by rimiiii** [PyProphet/pyprophet#104]
Hi 👋, I’m yurim in South Korea.
I am very impressed with the pyprophet tool you developed.
Thanks for providing a great tool.

I have a one question about pyprophet.
I am trying to implement mprophet's sub scores by referring to your code, but I couldn't find a code to calculate the sub scores.
The sub score is 8 scores developed by mprophet(intensity score, intensity correlation, coelution score etc).
Can you tell me where you calculated the subscore in your pyprophet code? If it's not in the code, is there a code or formula that you referenced for the calculation method?

Thank you so much.
Have a nice day :)

**Comment by grosenberger** [comment]
Hi yurim,

PyProphet only does machine learning and statistical validation. For the signal processing part, you need to use either mQuest (part of mProphet) or OpenSWATH (implemented as part of OpenMS). For S/MRM data, however, I recommend to use Skyline, which has mProphet implemented as well.

Best regards,
George

**Comment by rimiiii** [comment]
Thank you for replying :)

Best,
Yurim
