### ISSUE TITLE
Mapping d_scores with p-values

### ISSUE THREAD

**Issue by petercim** [PyProphet/pyprophet#14]
Not really an issue, more of a question: I was wondering if there's a way to map d_scores in the [FILE]_with_dscore.csv output to p-values (or q-values)?

**Comment by grosenberger** [comment]
The most recent version from GitHub (not PyPI) should report p-values, posterior error probabilites (pep) and q-values aside the d-score. You can try to install it directly with this command:

`pip install git+https://github.com/PyProphet/pyprophet.git`
