### ISSUE TITLE
"pyprophet score --threads=-1 ... "raise exception 

### ISSUE THREAD

**Issue by tachengxmu** [PyProphet/pyprophet#43]
with version 2.0.2. 
on centos 7.4 anaconda2 conda 4.5.11 python 2.7.15 

$ pyprophet score --threads=-1 ...

raise exception:

..../pyprophet/data_handling.py", line 30, in transform_threads
    value = multiprocessing.cpu_count()
NameError: global name 'multiprocessing' is not defined

Thanks.

**Comment by grosenberger** [comment]
Thanks! Addressed in #44 and released as ``2.0.3``.
