### ISSUE TITLE
Transition ids are not preserved 

### ISSUE THREAD

**Issue by hroest** [PyProphet/pyprophet#48]
When pyprophet exports data to TSV, it changes the transition id as follows:

https://github.com/PyProphet/pyprophet/blob/806b35b6072804d2a941754679930dcd4c23ec29/pyprophet/export.py#L245

Why is that the case? This means the transition ids in the export file in the column aggr_Fragment_Annotation are not matching the transition ids in the mzML / sqMass file any more.

**Comment by grosenberger** [comment]
I believe to remember that this was requested for compatibility with downstream tools, e.g. SWATH2stats that parses the annotation therein. Maybe it would be a better option to add an additional column that links the data in the table with the mzML sqMass files.

**Comment by hroest** [comment]
well, if we know what it does we can parse it correctly. Its a bit of a hassle as there is supposed to be one identifier for a transition and it would be nice if its the same in TraML, PQP, sqMass, mzML and the osw outfile :-)
