### ISSUE TITLE
pyprophet export ignores --out parameter

### ISSUE THREAD

**Issue by hroest** [PyProphet/pyprophet#49]
E.g.

```
$ time pyprophet export --in ../olgas_K121026_013_SW_Wayne_R3_d00.new.osw   --max_rs_peakgroup_qvalue 1.0 --out test.csv
Info: Reading peak group-level results.
Info: Reading transition-level results.
Info: Reading protein identifiers.

real    0m33.396s
user    0m25.228s
sys     0m5.372s
(py27_bleeding) hr@hr-Precision-5520:~/openmsall/builds/openms_trunk2/t5$ ls -ltrh
total 188M
-rw-rw-r-- 1 hr hr 188M Feb 20 13:31 olgas_K121026_013_SW_Wayne_R3_d00.mzML.gz.tsv
```

no test.csv file is preduced, instead the file is named after the "run" filename with the full "mzML" and "gz" attached: `schubert_chapter/raw/olgas_K121026_013_SW_Wayne_R3_d00.mzML.gz`

**Comment by grosenberger** [comment]
I recently changed this to restore compatibility with the requant workflow that required separate files. A combined table can be obtained by setting ``--format=legacy_merged``.

**Comment by hroest** [comment]
it is fine in general to have single files, but what was unexpected is that the filename will be "original mzML filename" + tsv and during mapping we did not expect that.
