### ISSUE TITLE
Py3 support

### ISSUE THREAD

**Issue by bretttully** [PyProphet/pyprophet#6]
Just wondering if there is any plans for py3 support? I've just run a 2to3 conversion and many tests pass, but many fail due to str/byte comparison issues. 

Cheers

**Comment by hroest** [comment]
we are happy to talk PR but the whole handling of strings is really annoying in Python3, especially when having a C++ part, so we havent put in the work yet to do it.

**Comment by grosenberger** [comment]
The new SQLite-enabled PyProphet implementation is compatible with Python 3: http://openswath.org/en/latest/docs/sqlite.html
