### ISSUE TITLE
pyprophet export ends w/o any output

### ISSUE THREAD

**Issue by mwalzer** [PyProphet/pyprophet#65]
Using the version from dockerhub
```
$~ pyprophet --version
pyprophet, version 2.1.3
```
The osw file is ~160M and produced by merging several osw, scoring ms1 ms2, doing peptide and protein levels in all 3 contexts. Then,
```
$~ pyprophet export --in=/scratch/runs_merged.osw --out=/scratch/whatever
Info: Reading peak group-level results.
Info: Reading transition-level results.
Info: Reading protein identifiers.
Info: Reading peptide-level results.
Info: Reading protein-level results.
```
results in **no** new files.  Same pipeline works well with `SGS`. Dunno if it is related to #49 
How can I check what is going on? Is there a debug or verbose flag? How could I check if my merged osw doesnt just contain garbage (I imagine something like COUNT ... WHERE SCORE_MS2.QVALUE < 0.05 == 0)?

**Comment by mwalzer** [comment]
run-specific context for each file works fine:
```
pyprophet score --in=file_1.osw --level=ms1 score --in=file_1.osw --level=ms2 
pyprophet peptide --in=file_1.osw --context=run-specific
pyprophet protein --in=file_1.osw --context=run-specific
pyprophet export --in=file_1.osw --out=legacy.tsv
```
$~ ls -lah *tsv
-rw-r--r--   1 walzer agroup 1.2M Jul 19 14:35 file_1.mzML.tsv
```

**Comment by grosenberger** [comment]
``pyprophet export`` by default already does some filtering. Can you try to set the peptide and protein level thresholds to 1.00? Does that result in any TSV files?

**Comment by mwalzer** [comment]
You mean `--max_rs_peakgroup_qvalue` & `--max_global_protein_qvalue` ?
Yep, that yields tsv files (:cry: this probably means either my data or my pqp is really bad?)
Small feature request: would be nice to have a notification/warning that all results have been filtered, hence no result file.

**Comment by grosenberger** [comment]
Yes, but if you built a sample-specific library, a common issue might be that RT normalization did not work out.

Thanks for the suggestion, we should definitely add such a warning.
