### ISSUE TITLE
Initialise default config class

### ISSUE THREAD

**Issue by bretttully** [PyProphet/pyprophet#7]
Add the following to the constructor of `_ConfigHolder` in https://github.com/PyProphet/pyprophet/blob/master/pyprophet/config.py

```
_fix_config_types(self.config)
```

This will ensure that the `CONFIG` is ready to be used after construction; currently the delimiters are defaulted to `'tab'` and this means running pyprophet from within python (i.e. not on the cmd line) doesn't work.

**Comment by cosmo-ethz** [comment]
Fixed this. Available at github and as version 0.24.1 on PyPI.

**Comment by cosmo-ethz** [comment]
please close the issue.

**Comment by bretttully** [comment]
👍
