### ISSUE TITLE
Note: Installing xgboost on MacOS Catalina 10.15 (pyprophet)

### ISSUE THREAD

**Issue by oliveralka** [PyProphet/pyprophet#74]
I ran into a pyprophet segmentation fault error after upgrading to MacOS Catalina 10.15 .

This is due to an incompatibility with the current xgboost installation.

Here is a reference with a workaround for this issue https://github.com/dmlc/xgboost/issues/4949

Using the workaround to install xgboost, pyprophet runs without issues.

**Comment by grosenberger** [comment]
Thanks for posting the workaround here, let's keep this issue open until it is fixed.
