### ISSUE TITLE
Error: At least 10 decoy groups and 10 target groups are required

### ISSUE THREAD

**Issue by lmangnier** [PyProphet/pyprophet#77]
Hi there, 

I'm pretty novice in proteomic tools and I try to use OpenSwath on our own data.

I start launching this command "OpenSwathWorkflow "
                        "-in {input} "
                        "-tr iRTassays.pqp "
                        "-tr_irt iRTassays.TraML "
                        "-mz_extraction_window 10 -ppm "
                        "-RTNormalization:alignmentMethod linear "
                        "-Scoring:stop_report_after_feature 5 "
                        "-swath_windows_file {config[window_file]} "
                        "-Library:override_group_label_check "
                        "-sort_swath_maps "
                        "-out_osw {output} "
                        " > {log.stdout} 2> {log.stderr}"

The parameter -Library:override_group_label_check was added because of the warning I had : "Warning: Found multiple peptide sequences for peptide label group light. This is most likely an error and to fix this, a new peptide label group will be inferred - to override this decision, please use the override_group_label_check parameter". Even if I add the option, nothing seems to change. 

The command works fine it seems, after that I can merge my osw files. But when I try to launch scoring command with pyprophet score I have "Error: At least 10 decoy groups and 10 target groups are required". 

I don't understand why I have this kind of issue, Do I add some other parameters in previous steps ?

Thanks for your help. 

Loïc.

**Comment by grosenberger** [comment]
Hi Loïc, what happens if you don't merge, but directly apply ``pyprophet score`` to one of your OSW files?

**Comment by lmangnier** [comment]
Unfortunately, I have the same kind of error on a single file. 

Are there some additional functions to check if osw files are fine ?

Loïc.

**Comment by grosenberger** [comment]
How did you generate the spectral library? After spectrast2tsv.py or OpenSwathAssayGenerator, did you apply OpenSwathDecoyGenerator to append decoys?

**Comment by lmangnier** [comment]
I relaunch the spectral library generation with OpenSwathAssayGenerator and add decoys with OpenSwathDecoyGenerator and it seems to work. 

Thanks a lot for your help.

Loïc.
