### ISSUE TITLE
OpenSWATH IPF workflow errored.

### ISSUE THREAD

**Issue by andyzim111** [PyProphet/pyprophet#84]
Hi,OpenMS devs.

I found a runtime error when I run OpenSWATH IPF workflow as followings.

    OpenSwathAssayGenerator.exe -in irt.tsv -out irt.TraML -product_lower_mz_limit 100 -product_mz_threshold 0.05 -swath_windows_file *.txt

    OpenSwathAssayGenerator.exe -in *.tsv -out lib.os.tsv -product_lower_mz_limit 100 -product_mz_threshold 0.05 -swath_windows_file *.txt -unimod_file Phos.unimod.xml -enable_ipf

    OpenSwathDecoyGenerator.exe -in lib.os.tsv -out lib.os.pqp

thus far everything is ok

    OpenSwathWorkflow.exe -readOptions workingInMemory -sort_swath_maps -rt_extraction_window 1200 -use_ms1_traces -enable_uis_scoring -tr_irt irt.TraML -tr lib.os.pqp -threads 48 -swath_windows_file *.txt -out_osw *.osw -in *.mzXML

but in this step get a Application Error (Access Violation 0xc0000005) Offset 0x0000000000013fb0 (in OpenMS.dll)
this error info is retrieved from eventvwr.msc -> Windows Log -> Application 

and OpenSwathWorkflow's output(see POSTSCRIPT) seems to be ok , so how to overcome this error?
By the way, I am using openMS 2.5.

Best regards.

--POSTSCRIPT--

Will load iRT transitions and try to find iRT peptides
Progress of 'Load TraML file':

-- done [took 1.61 s (CPU), 0.05 s (Wall)] -- 
Progress of 'Extract iRT chromatograms':

-- done [took 16.16 s (CPU), 8.27 s (Wall)] -- 
Progress of 'Retention time normalization':
Will analyse 21 peptides with a total of 126 transitions 
WARNING in SignalToNoiseEstimatorMedian: 2.39868% of all Signal-to-Noise estimates are too high, because the median was found in the rightmost histogram-bin. You should consider increasing 'max_intensity' (and maybe 'bin_count' with it, to keep bin width reasonable)
WARNING in SignalToNoiseEstimatorMedian: 2.31596% of all Signal-to-Noise estimates are too high, because the median was found in the rightmost histogram-bin. You should consider increasing 'max_intensity' (and maybe 'bin_count' with it, to keep bin width reasonable)
WARNING in SignalToNoiseEstimatorMedian: 2.48139% of all Signal-to-Noise estimates are too high, because the median was found in the rightmost histogram-bin. You should consider increasing 'max_intensity' (and maybe 'bin_count' with it, to keep bin width reasonable)
WARNING in SignalToNoiseEstimatorMedian: 2.64682% of all Signal-to-Noise estimates are too high, because the median was found in the rightmost histogram-bin. You should consider increasing 'max_intensity' (and maybe 'bin_count' with it, to keep bin width reasonable)
<WARNING in SignalToNoiseEstimatorMedian: 2.39868% of all Signal-to-Noise estimates are too high, because the median was found in the rightmost histogram-bin. You should consider increasing 'max_intensity' (and maybe 'bin_count' with it, to keep bin width reasonable)> occurred 5 times
WARNING in SignalToNoiseEstimatorMedian: 1.65426% of all Signal-to-Noise estimates are too high, because the median was found in the rightmost histogram-bin. You should consider increasing 'max_intensity' (and maybe 'bin_count' with it, to keep bin width reasonable)
rsq: 0.849468 points: 21
rsq: 0.936791 points: 20
rsq: 0.99906 points: 19

-- done [took 1.42 s (CPU), 1.31 s (Wall)] -- 
Will analyze 672261 transitions in total.
Progress of 'Extracting and scoring transitions':

  0.99 %               Thread 7_0 will analyze 7 compounds and 796 transitions from SWATH 13 (batch 0 out of 1)
Thread 47_0 will analyze 7 compounds and 803 transitions from SWATH 16 (batch 0 out of 1)
Thread 30_0 will analyze 14 compounds and 790 transitions from SWATH 19 (batch 0 out of 1)
Thread 40_0 will analyze 10 compounds and 425 transitions from SWATH 14 (batch 0 out of 1)
Thread 26_0 will analyze 20 compounds and 1599 transitions from SWATH 35 (batch 0 out of 1)
Thread 14_0 will analyze 10 compounds and 910 transitions from SWATH 23 (batch 0 out of 1)
Thread 28_0 will analyze 6 compounds and 266 transitions from SWATH 10 (batch 0 out of 1)
Thread 25_0 will analyze 21 compounds and 1710 transitions from SWATH 42 (batch 0 out of 1)
Thread 2_0 will analyze 14 compounds and 3024 transitions from SWATH 22 (batch 0 out of 1)
Thread 16_0 will analyze 5 compounds and 510 transitions from SWATH 15 (batch 0 out of 1)
Thread 31_0 will analyze 8 compounds and 353 transitions from SWATH 25 (batch 0 out of 1)
Thread 44_0 will analyze 5 compounds and 89 transitions from SWATH 12 (batch 0 out of 1)
Thread 18_0 will analyze 8 compounds and 746 transitions from SWATH 20 (batch 0 out of 1)
Thread 39_0 will analyze 11 compounds and 966 transitions from SWATH 33 (batch 0 out of 1)
Thread 20_0 will analyze 2 compounds and 161 transitions from SWATH 3 (batch 0 out of 1)
Thread 36_0 will analyze 20 compounds and 3116 transitions from SWATH 37 (batch 0 out of 1)
Thread 17_0 will analyze 3 compounds and 190 transitions from SWATH 8 (batch 0 out of 1)
Thread 24_0 will analyze 2 compounds and 342 transitions from SWATH 5 (batch 0 out of 1)
Thread 3_0 will analyze 14 compounds and 640 transitions from SWATH 26 (batch 0 out of 1)
Thread 46_0 will analyze 28 compounds and 2467 transitions from SWATH 47 (batch 0 out of 1)
Thread 12_0 will analyze 18 compounds and 1234 transitions from SWATH 32 (batch 0 out of 1)
Thread 11_0 will analyze 5 compounds and 177 transitions from SWATH 11 (batch 0 out of 1)
Thread 29_0 will analyze 16 compounds and 2039 transitions from SWATH 31 (batch 0 out of 1)
Thread 0_0 will analyze 33 compounds and 3835 transitions from SWATH 38 (batch 0 out of 1)
Thread 41_0 will analyze 14 compounds and 3012 transitions from SWATH 28 (batch 0 out of 1)
Thread 42_0 will analyze 27 compounds and 3880 transitions from SWATH 40 (batch 0 out of 1)
Thread 10_0 will analyze 18 compounds and 1993 transitions from SWATH 43 (batch 0 out of 1)
Thread 37_0 will analyze 3 compounds and 18 transitions from SWATH 2 (batch 0 out of 1)
Thread 22_0 will analyze 4 compounds and 102 transitions from SWATH 7 (batch 0 out of 1)
Thread 6_0 will analyze 10 compounds and 601 transitions from SWATH 30 (batch 0 out of 1)
Thread 35_0 will analyze 15 compounds and 591 transitions from SWATH 24 (batch 0 out of 1)
Thread 13_0 will analyze 36 compounds and 2930 transitions from SWATH 44 (batch 0 out of 1)
Thread 21_0 will analyze 18 compounds and 977 transitions from SWATH 29 (batch 0 out of 1)
Thread 38_0 will analyze 24 compounds and 3072 transitions from SWATH 34 (batch 0 out of 1)
Thread 32_0 will analyze 27 compounds and 3155 transitions from SWATH 39 (batch 0 out of 1)
Thread 43_0 will analyze 3 compounds and 192 transitions from SWATH 4 (batch 0 out of 1)
Thread 34_0 will analyze 19 compounds and 2966 transitions from SWATH 36 (batch 0 out of 1)
Thread 15_0 will analyze 24 compounds and 3389 transitions from SWATH 46 (batch 0 out of 1)
Thread 4_0 will analyze 17 compounds and 1371 transitions from SWATH 27 (batch 0 out of 1)
Thread 19_0 will analyze 33 compounds and 4938 transitions from SWATH 49 (batch 0 out of 1)
Thread 9_0 will analyze 3 compounds and 569 transitions from SWATH 9 (batch 0 out of 1)
Thread 1_0 will analyze 31 compounds and 3524 transitions from SWATH 50 (batch 0 out of 1)
Thread 23_0 will analyze 6 compounds and 260 transitions from SWATH 18 (batch 0 out of 1)
Thread 45_0 will analyze 28 compounds and 3344 transitions from SWATH 41 (batch 0 out of 1)
Thread 8_0 will analyze 16 compounds and 2479 transitions from SWATH 45 (batch 0 out of 1)
Thread 33_0 will analyze 10 compounds and 1053 transitions from SWATH 17 (batch 0 out of 1)
Thread 27_0 will analyze 27 compounds and 2138 transitions from SWATH 48 (batch 0 out of 1)
Thread 5_0 will analyze 17 compounds and 1645 transitions from SWATH 21 (batch 0 out of 1)
Thread 37_0 will analyze 3 compounds and 18 transitions from SWATH 2 (batch 1 out of 1)

    3.96 %               Thread 37_0 will analyze 31 compounds and 2254 transitions from SWATH 51 (batch 0 out of 1)
<WARNING in SignalToNoiseEstimatorMedian: 2.64682% of all Signal-to-Noise estimates are too high, because the median was found in the rightmost histogram-bin. You should consider increasing 'max_intensity' (and maybe 'bin_count' with it, to keep bin width reasonable)> occurred 2 times

**Comment by grosenberger** [comment]
Hi, we unfortunately don't have a lot of experience with OpenSWATH on Windows. But I could imagine that you are running out of memory though. You can try the following two options:
- Cache the raw data on disk
- Lower the chunk size to onky few hundreds or thousands of peak groups to split the analysis in more batches.

**Comment by cbielow** [comment]
This most certainly looks like a bug in OpenSwathWorkflow, since what you get is the equivalent of a segfault on Linux, a.k.a the program tries to read/write to memory it's not supposed to.
This issue would be best reported in https://github.com/OpenMS/OpenMS/issues. Could you provide your input data which causes the crash?!
