### ISSUE TITLE
pyprophet ipf error

### ISSUE THREAD

**Issue by summerghw** [PyProphet/pyprophet#88]
Hi,
when i try to use pyprophet, this error appear:
`root@61d6818b7369:/data/ftp.peptideatlas.org# pyprophet ipf --in=merged.osw
Info: Starting IPF (Inference of PeptidoForms).
Info: Reading precursor-level data.
Info: Preparing precursor-level data.
Info: Conducting precursor-level inference.
Traceback (most recent call last):
  File "/usr/local/bin/pyprophet", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyprophet/main.py", line 122, in ipf
    infer_peptidoforms(infile, outfile, ipf_ms1_scoring, ipf_ms2_scoring, ipf_h0, ipf_grouped_fdr, ipf_max_precursor_pep, ipf_max_peakgroup_pep, ipf_max_precursor_peakgroup_pep, ipf_max_transition_pep)
  File "/usr/local/lib/python3.5/dist-packages/pyprophet/ipf.py", line 366, in infer_peptidoforms
    precursor_data = precursor_inference(precursor_table, ipf_ms1_scoring, ipf_ms2_scoring, ipf_max_precursor_pep, ipf_max_precursor_peakgroup_pep)
  File "/usr/local/lib/python3.5/dist-packages/pyprophet/ipf.py", line 323, in precursor_inference
    prec_pp_data = apply_bm(precursor_data_bm)
  File "/usr/local/lib/python3.5/dist-packages/pyprophet/ipf.py", line 284, in apply_bm
    pp_data.columns = ['feature_id','hypothesis','likelihood_prior']
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py", line 5080, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py", line 638, in _set_axis
    self._data.set_axis(axis, labels)
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/internals/managers.py", line 155, in set_axis
    'values have {new} elements'.format(old=old_len, new=new_len))
ValueError: Length mismatch: Expected axis has 2 elements, new values have 3 elements
`
could you help, thank you a lot

**Comment by grosenberger** [comment]
Could you please provide further information so I can try to reproduce the issue? Ideally the following information would be available:

- Software versions used
- Full set of used CLI parameters
- Minimal example OSW files to reproduce the issue

**Comment by summerghw** [comment]
1.software version: pyprophet, version 2.1.3
2.openswath cmd
`OpenSwathAssayGenerator-in greenmonkey.TraML \
-out greenmonkey_optimized.TraML \
-swath_windows_file greenmonkey_windos.txt \ 
-enable_ipf \
-unimod_file unimod_phospho.xml \
-min_transitions 6 \
-max_transitions 6 \
-allowed_fragment_types b,y \
-allowed_fragment_charges 1,2,3,4 \
-enable_detection_specific_losses \
-enable_detection_unspecific_losses \
-precursor_mz_threshold 0.025 \
-precursor_lower_mz_limit 400 \
-precursor_upper_mz_limit 1200 \
-product_mz_threshold 0.025 \
-product_lower_mz_limit 350 \
-product_upper_mz_limit 2000 \
-max_num_alternative_localizations 10000 \
-disable_identification_ms2_precursors \
-disable_identification_specific_losses \
-enable_identification_unspecific_losses \
-enable_swath_specifity `
`OpenSwathDecoyGenerator -in greenmonkey_optimized.TraML \
-allowed_fragment_types b,y \
-allowed_fragment_charges 1,2,3,4 \
-enable_detection_specific_losses \
-enable_detection_unspecific_losses \
-product_mz_threshold 0.025 \
-out greenmonkey_optimized_decoys.TraML `
`TargetedFileConverter -in greenmonkey_optimized.TraML \
-out greenmonkey_optimized.PQP`
`#!/bin/bash
date
for i in 'less mzML.list'
        do
        {
                OpenSwathWorkflow -in ${i} -tr greenmonkey_optimized_decoys.PQP -swath_windows_file greenmonkey_windows_analysis.txt -use_ms1_traces -enable_uis_scoring  -out_tsv osw_${i} ;
        }&
        done
        wait
        date `

pyprophet cmd
`pyprophet merge --template=greenmonkey_optimized_decoys.PQP --out=merged.osw *.osw
pyprophet score --in=merged.osw --level=ms1 \
score --in=merged.osw --level=ms2 \
score --in=merged.osw --level=transition`

`pyprophet peptide --in=merged.osw --context=run-specific \
peptide --in=merged.osw --context=experiment-wide \
peptide --in=merged.osw --context=global`

`pyprophet protein --in=merged.osw --context=run-specific \
protein --in=merged.osw --context=experiment-wide \
protein --in=merged.osw --context=global`

`pyprophet ipf --in=merged.osw`

`pyprophet export --in=merged.osw --out=legacy.tsv`

3.merge.osw [https://pan.baidu.com/s/1zUosy167qVOpo5jh5EBjhw](url)  passwd: vf3g
when i try to export ,there is no new file, i tryed to use `pyprophet export --in=merged.osw --out=legacy.tsv --max_rs_peakgroup_qvalue 1 --max_global_protein_qvalue 1 --max_global_peptide_qvalue 1 --max_transition_pep 1` 
but still not work.   is that means my library  is not correct.

**Comment by grosenberger** [comment]
I unfortunately have issues to access the link and to download the files. But here are a few comments to the parameters:

- OpenSwathAssayGenerator & OpenSwathDecoyGenerator: You used several parameters that are of more experimental nature or should only be used in specific settings. Could you please try to use my default parameters?

``OpenSwathAssayGenerator -in library.tsv -out library_targets.pqp -min_transitions 6 -max_transitions 6 -enable_ipf -unimod_file unimod_phospho.xml -disable_identification_ms2_precursors -disable_identification_specific_losses
``
``
OpenSwathDecoyGenerator -in $cache/library_targets.pqp -out $cache/library.pqp
``
