### ISSUE TITLE
Decoys peptides are counted in pyprophet statistics

### ISSUE THREAD

**Issue by jcharkow** [PyProphet/pyprophet#89]
Not sure if this is intended behavior but when displaying the total number of peptides and proteins identified in global context it seems that decoys are included in this count. 
If this is intended behavior I was thinking it might be useful to also display the counts with no decoys?

**Comment by grosenberger** [comment]
Thanks for the notice, this might indeed be unexpected behaviour. Only targets are now reported in PyProphet 2.1.6.

**Comment by jcharkow** [comment]
Great thank you for the fix!
